### PR TITLE
splash screen and request permission added

### PR DESCRIPTION
**Pull request by JoykishanSharma**
Splash Screen is added
Read External Storage Permission request is added

### CODE REVIEW

**Review by Detective-Khalifah — APPROVED** [review]

**Review by Detective-Khalifah — COMMENTED** [review]
I can only see splash screen addition, but nothing permission request. Looks good, BTW

**Comment by JoykishanSharma** [comment]
If a device is running Android 6.0 (API level 23) or higher, it is highly [recommended](https://developer.android.com/training/permissions/requesting) to ask the user to grant the [dangerous permissions](https://stackoverflow.com/questions/32635704/android-permission-doesnt-work-even-if-i-have-declared-it) at runtime. :relaxed:

My device has Android 7.1.1, so it wasn't allowing the app to access the storage automatically. 
Permission Request only shows once in the beginning of the [SplashActivity](https://github.com/Red-Deathh/ReadMp3FilesFromStorage/blob/master/app/src/main/java/com/derron/readmp3filesfromstorage/SplashActivity.java). 
If you uninstall and then reinstall the app, it will ask for the access permission (if Android 6.0 or higher).:relaxed:

Thanks for the merge  :relaxed: :thumbsup:

**Comment by JoykishanSharma** [comment]
> I can only see splash screen addition, but nothing permission request. Looks good, BTW

If a device is running Android 6.0 (API level 23) or higher, it is highly [recommended](https://developer.android.com/training/permissions/requesting) to ask the user to grant the [dangerous permissions](https://stackoverflow.com/questions/32635704/android-permission-doesnt-work-even-if-i-have-declared-it) at runtime. :relaxed:

My device has Android 7.1.1, so it wasn't allowing the app to access the storage automatically. 
Permission Request only shows once in the beginning of the [SplashActivity](https://github.com/Red-Deathh/ReadMp3FilesFromStorage/blob/master/app/src/main/java/com/derron/readmp3filesfromstorage/SplashActivity.java). 
If you uninstall and then reinstall the app, it will ask for the access permission (if Android 6.0 or higher).:relaxed:

Thanks for the merge  :relaxed: :thumbsup:

**Comment by Detective-Khalifah** [comment]
True. I wasn't paying enough attention.

**Pull request merged**
